---
- name: BTRFS storage config
  hosts: all

  tasks:
  - name: Create a BTRFS partition for LXD storage
    parted:
      device: /dev/sdc
      number: 1
      state: present
      fs_type: btrfs

  - name: Create a BTRFS filesystem for LXD storage
    community.general.filesystem:
      fstype: btrfs
      dev: /dev/sdc1

  - name: Create mount point
    file:
      path: /mnt/lxd
      state: directory
      mode: '0755'

  - name: Mount LXD storage file system
    mount:
      path: /mnt/lxd
      src: /dev/sdc1
      fstype: btrfs
      state: mounted
