---
- name: Docker test environment provision
  hosts: all
  become: yes

# Shared repo checkout and pip packages example:
# https://github.com/cheretbe/notes/blob/master/vagrant.md#ansible-provision
  tasks:
    - name: Checkout shared playbooks repo
      git:
        repo: "https://github.com/cheretbe/ansible-playbooks.git"
        dest: "/ansible-playbooks"

    - include_role: name="/ansible-playbooks/linux-utils"
    - include_role: name="/ansible-playbooks/docker-ce"

    - name: Add user 'vagrant' to group 'docker'
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Install 'python3-pip' package
      apt:
        name: "python3-pip"
        # Fix for warning message "Could not find aptitude. Using apt-get instead"
        force_apt_get: yes
        update_cache: no

    - name: Install Python 3 packages
      pip:
        name: ["packaging", "requests", "invoke", "pytest", "PyInquirer",
               "molecule[docker]", "docker", "ansible-lint", "flake8",
               "testinfra"]
        executable: pip3
